project_id = "sgezwrrnlboggimmusnj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "http://127.0.0.1:54322"
additional_redirect_urls = ["https://127.0.0.1:3000"]
email_double_confirm_changes = true
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.compare-reports]
verify_jwt = false